# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CoPilot < Formula
  desc "Co-pilot is a developer tool for automating common tasks on a spring boot project."
  homepage "https://devdimensionlab.github.io/"
  version "0.6.25"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/devdimensionlab/co-pilot/releases/download/v0.6.25/co-pilot_0.6.25_Darwin_arm64.tar.gz"
      sha256 "21d6c1ab530f69cd7a8e9f8285b0b35d11cf53f2cd45f0aac95a143ad46212d8"

      def install
        bin.install "co-pilot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devdimensionlab/co-pilot/releases/download/v0.6.25/co-pilot_0.6.25_Darwin_x86_64.tar.gz"
      sha256 "a159c0c90b4821e495379b3e9c512bc147937f87ba06c592051700e37b936c1c"

      def install
        bin.install "co-pilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devdimensionlab/co-pilot/releases/download/v0.6.25/co-pilot_0.6.25_Linux_arm64.tar.gz"
      sha256 "83693cd7e74443ae00480e92a929cd578c03825e4090ab33119e48ba4a32305a"

      def install
        bin.install "co-pilot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devdimensionlab/co-pilot/releases/download/v0.6.25/co-pilot_0.6.25_Linux_x86_64.tar.gz"
      sha256 "121502e6fadcb4ff09f967052167954024d7a7a8b5967e0bfaedc12b021fcae2"

      def install
        bin.install "co-pilot"
      end
    end
  end
end
